### ISSUE TITLE
unused value error

### ISSUE THREAD

**Issue by choonho** [spaceone-dev/python-core#33]
In a scheduler configuration, if there is PORT like unused value,
error occurs.

Traceback (most recent call last):
  File "/usr/local/bin/spaceone", line 33, in <module>
    sys.exit(load_entry_point('spaceone-core==1.2.1.2', 'console_scripts', 'spaceone')())
  File "/usr/local/lib/python3.8/site-packages/spaceone_core-1.2.1.2-py3.8.egg/spaceone/core/command.py", line 241, in main
    _initialize_config(args)
  File "/usr/local/lib/python3.8/site-packages/spaceone_core-1.2.1.2-py3.8.egg/spaceone/core/command.py", line 162, in _initialize_config
    _set_server_config(args)
  File "/usr/local/lib/python3.8/site-packages/spaceone_core-1.2.1.2-py3.8.egg/spaceone/core/command.py", line 139, in _set_server_config
    _set_file_config(params['config'])
  File "/usr/local/lib/python3.8/site-packages/spaceone_core-1.2.1.2-py3.8.egg/spaceone/core/command.py", line 94, in _set_file_config
    config.set_file_conf(path)
  File "/usr/local/lib/python3.8/site-packages/spaceone_core-1.2.1.2-py3.8.egg/spaceone/core/config/__init__.py", line 106, in set_file_conf
    set_global(**global_conf)
  File "/usr/local/lib/python3.8/site-packages/spaceone_core-1.2.1.2-py3.8.egg/spaceone/core/config/__init__.py", line 80, in set_global
    raise ValueError(f'Value type is invalid. (GLOBAL.{key} = {value_type_name})')
ValueError: Value type is invalid. (GLOBAL.PORT = NoneType)

**Comment by whdalsrnt** [comment]
Issue: Merge NoneType Config
Change Code:
`if not isinstance(value, type(global_conf[key])) and global_conf[key] is not None:
    value_type_name = type(global_conf[key]).__name__raise ValueError(f'Value type is invalid. (GLOBAL.{key} = {value_type_name})')`
